import type { Metadata } from "next";
import {MenubarHeeader} from "@/components/menubarHeader";
export const metadata: Metadata = {
  title: "Next Auth app",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <MenubarHeeader/>
        {children}
    </>
  );
}
